name: Lada Nakonechna
title: Lada's Website
email: admin@ladanakonechna.com
description: >-
  Lada Nakonechna is an artist who lives and works in Kyiv.  
  In her works, Nakonechna uses various artistic means, 
  such as drawings, photographs, installations, and performances.

baseurl: ""
url: "https://ladanakonechna.com"
twitter_username: ""
github_username:  ""

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - /third-party

collections:
  works:
    output: true
    permalink: /works/:name
  exhibitions:
    output: true
    permalink: /exhibitions/:name
  writing:
    output: true
    permalink: /writing/:name
