name: Lada Nakonechna
title: Lada's Website
email: admin@ladanakonechna.com
description: >-
  Lada Nakonechna is an artist who lives and works in Kyiv.  
  In her works, Nakonechna uses various artistic means, 
  such as drawings, photographs, installations, and performances.

baseurl: "/ln-website"
url: "https://jor-m.github.io/ln-website/"
twitter_username: ""
github_username:  ""

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - third-party/
  - imported/

include:
  - _works/

collections:
  works:
    output: true
    permalink: /works/:name
